// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Krypton {
	
	
	public partial class CreateGame {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label IDLabel;
		
		protected System.Web.UI.WebControls.Label MaxLabel;
		
		protected System.Web.UI.WebControls.TextBox MaxBox;
	}
}
