// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Krypton {
	
	
	public partial class Game {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;

		protected System.Web.UI.WebControls.Label Time;

		protected System.Web.UI.WebControls.Label Score;

		protected System.Web.UI.WebControls.Label RoundCurrent;

		protected System.Web.UI.WebControls.Label RoundMax;
		
		protected System.Web.UI.WebControls.Label card1;
		
		protected System.Web.UI.WebControls.Label card2;
		
		protected System.Web.UI.WebControls.Label card3;
		
		protected System.Web.UI.WebControls.Label card4;
		
		protected System.Web.UI.WebControls.Label card5;
		
		protected System.Web.UI.WebControls.Label card6;
		
		protected System.Web.UI.WebControls.Label label;
		
		protected System.Web.UI.WebControls.Button newCardsButton;
		
		protected System.Web.UI.WebControls.TextBox answerBox;
		
		protected System.Web.UI.WebControls.Button checkCardsButton;
	}
}
